apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: menu-api
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: gator-bites
spec:
  source:
    git:
      url: https://github.com/aullom1/menu-api
      ref:
        branch: main
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
